// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ReorderDatabase.Data;

#nullable disable

namespace ReorderDatabase.Data.Migrations
{
    [DbContext(typeof(NoteContext))]
    [Migration("20211105153052_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0-rc.2.21480.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ReorderDatabase.Data.Entities.Note", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<decimal>("Denominator")
                        .HasColumnType("decimal(20,0)");

                    b.Property<decimal>("Numerator")
                        .HasColumnType("decimal(20,0)");

                    b.Property<decimal>("Order")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("decimal(18,2)")
                        .HasComputedColumnSql("CAST([Numerator] AS DECIMAL) / CAST([Denominator] AS DECIMAL)", true);

                    b.Property<string>("Text")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Notes");

                    b.HasData(
                        new
                        {
                            Id = -10,
                            Denominator = 1m,
                            Numerator = 1m,
                            Order = 0m,
                            Text = "Ronaldo"
                        },
                        new
                        {
                            Id = -9,
                            Denominator = 1m,
                            Numerator = 2m,
                            Order = 0m,
                            Text = "Roberto Baggio"
                        },
                        new
                        {
                            Id = -8,
                            Denominator = 1m,
                            Numerator = 3m,
                            Order = 0m,
                            Text = "Ferenc Puskás"
                        },
                        new
                        {
                            Id = -7,
                            Denominator = 1m,
                            Numerator = 4m,
                            Order = 0m,
                            Text = "Marco van Basten"
                        },
                        new
                        {
                            Id = -6,
                            Denominator = 1m,
                            Numerator = 5m,
                            Order = 0m,
                            Text = "Stanley Matthews"
                        },
                        new
                        {
                            Id = -5,
                            Denominator = 1m,
                            Numerator = 6m,
                            Order = 0m,
                            Text = "Lev Yashin"
                        },
                        new
                        {
                            Id = -4,
                            Denominator = 1m,
                            Numerator = 7m,
                            Order = 0m,
                            Text = "Alfredo Di Stéfano"
                        },
                        new
                        {
                            Id = -3,
                            Denominator = 1m,
                            Numerator = 8m,
                            Order = 0m,
                            Text = "Diego Maradonna"
                        },
                        new
                        {
                            Id = -2,
                            Denominator = 1m,
                            Numerator = 9m,
                            Order = 0m,
                            Text = "Bobby Moore"
                        },
                        new
                        {
                            Id = -1,
                            Denominator = 1m,
                            Numerator = 10m,
                            Order = 0m,
                            Text = "Pelé"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
